// public class errorhandling {
//     public static void main(String[] args) {
//          int a=10;int b=0;
//          try{
//             int c=a/b;
//             System.out.println(c);
//          }
//         catch( Exception e){
//             System.out.println(" we can not divided by zero");
//         }
    
//         System.out.println("hello");
//         System.out.println("hii");
//         System.out.println("byee");
// }
//      public class errorhandling{
//       public static void main(String[] args)

// {
//         int [] arr={1,2,3,4};
//         try {
//             System.out.println(arr[6]);
            
//         } catch ( ArrayIndexOutOfBoundsException e) {
//             System.out.println(e);
//             System.out.println("we can not accec the index 6th because it is not in  bound   --"+e.getMessage());
            

//         }
//         catch(ArithmeticException e){
//             System.out.println(e);
//         }
//         finally{
            
//         }

//       }
//     }
    
   // we can make mutliple catch with repect to try

   public class errorhandling{
    public static void main(String[] args){

        int[]arr={2,3,4,4,6};
        
        
    }
}

